filebeat.inputs:
# The following block is sending every *.log files under
# /var/log/calm/*.log to the endpoint configured
# at the end of the file.
- type: log
  processors:
  - add_fields:
      target: 'calm_metadata'
      fields:
        "category": "system"
        "application": "app1"
        "send_to_es": "true"
  enabled: true
  paths:
    - /var/log/calm/*.log

output.logstash:
  hosts: ["http://logstash-staging.simplycalm.net:5044"]
  ttl: 60
  pipelining: 0
  loadbalance: true
  ssl.enabled: false

logging.level: debug # logging level for filebeat itself
