---
#
# Installing Cloudwatch Exporter
#
- hosts: "{{ ip }}"
  remote_user: ec2-user
  vars_files:
    - ../../output.yml
  vars:
    cloudwatch_exporter_version: 0.10.0
  tasks:
    - name: Enable amazon corretto8
      command: amazon-linux-extras enable corretto8
      become: yes

    - name: Install amazon corretto8
      yum:
        name: java-1.8.0-amazon-corretto
        state: present
        become: yes

    - name: create group
      group:
        name: cloudwatch-exporter
        state: present
      become: yes

    - name: create user
      user:
        name: cloudwatch-exporter
        group: cloudwatch-exporter
        createhome: no
        system: yes
        state: present
      become: yes

    - name: create opt directory
      file:
        path: /opt/prometheus
        state: directory
      become: yes

    - name: download cloudwatch exporter
      get_url:
        url: https://search.maven.org/remotecontent?filepath=io/prometheus/cloudwatch/cloudwatch_exporter/{{ cloudwatch_exporter_version }}/cloudwatch_exporter-{{ cloudwatch_exporter_version }}-jar-with-dependencies.jar
        dest: /opt/prometheus
      become: yes

    - name: Copy cloudwatch exporter shell script
      copy:
        src: ./cloudwatch_exporter.sh
        dest: /usr/local/bin/cloudwatch_exporter.sh
      become: yes

    - name: Copy cloudwatch exporter config
      copy:
        src: ./cloudwatch_exporter_config.yaml
        dest: /opt/prometheus/cloudwatch_exporter_config.yaml
      become: yes

    - name: install unit file to systemd
      copy:
        src: cloudwatch_exporter.service
        dest: /etc/systemd/system/cloudwatch_exporter.service
      become: yes

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: cloudwatch_exporter.service
      become: yes
