route:
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: default-mailbox
  routes:
    - receiver: oncall-mailbox
      match:
        type: out-of-hours

receivers:
- name: default-mailbox
  email_configs:
  - to: {{ default_mailbox }}
    from: {{ default_mailbox }}
    smarthost: smtp.gmail.com:587
    auth_username: "{{ default_mailbox }}"
    auth_identity: "{{ default_mailbox }}"
    auth_password: "{{ alerts_password }}"

- name: oncall-mailbox
  email_configs:
  - to: {{ oncall_mailbox }}
    from: {{ oncall_mailbox }}
    smarthost: smtp.gmail.com:587
    auth_username: "{{ oncall_mailbox }}"
    auth_identity: "{{ oncall_mailbox }}"
    auth_password: "{{ oncall_password }}"
