{
 "title": "CALM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Instance Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal{job=\"EC2 Node Exporter\"} - node_memory_MemFree{job=\"EC2 Node Exporter\"}) / (node_memory_MemTotal{job=\"EC2 Node Exporter\"} )) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Instance Filesystem Free Space (GB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_free{job=\"EC2 Node Exporter\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic Total (MB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) ((node_network_receive_bytes / 1024 / 1024) + (node_network_transmit_bytes / 1024 / 1024))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Connected to Alertmanager",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_alertmanagers_discovered"
      }
     ]
    },
    {
     "title": "Prometheus Restarts (Last 15 minutes)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "changes(process_start_time_seconds{job=~\"prometheus|pushgateway|alertmanager\"}[15m])"
      }
     ]
    },
    {
     "title": "Prometheus Discovered Targets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(prometheus_sd_discovered_targets)"
      }
     ]
    },
    {
     "title": "Prometheus Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_build_info{branch=\"HEAD\", goversion=\"go1.14.6\", instance=\"localhost:80\", job=\"prometheus\", revision=\"983ebb4a513302315a8117932ab832815f85e3d2\", version=\"2.20.1\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Prometheus Time Series",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count({__name__=~\".+\"})",
       "legendFormat": "Time Series"
      }
     ]
    },
    {
     "title": "Prometheus TSDB Failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_reloads_failures_total"
      }
     ]
    },
    {
     "title": "Prometheus Jobs Up",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "count by (job) (up)", "legendFormat": "{{ job }}" }
     ]
    },
    {
     "title": "Prometheus Exporter Scraping (Seconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=~\".*Prometheus\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal{instance=~\".*Prometheus\"} - node_memory_MemFree{instance=~\".*Prometheus\"} - (node_memory_Cached{instance=~\".*Prometheus\"} + node_memory_Buffers{instance=~\".*Prometheus\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached{instance=~\".*Prometheus\"} + node_memory_Buffers{instance=~\".*Prometheus\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree{instance=~\".*Prometheus\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal{instance=~\".*Prometheus\"} - node_memory_SwapFree{instance=~\".*Prometheus\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Prometheus Rule Evaluation Failures",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_rule_evaluation_failures_total[3m])",
       "legendFormat": "{{ rule_group }}"
      }
     ]
    },
    {
     "title": "CPU Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"iowait\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"user\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"system\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=~\".*irq\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Disk Space Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail{instance=~\".*Prometheus\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\".*Prometheus\",device!~'rootfs'})",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alertmanager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"iowait\",instance=~\".*Alertmanager\"}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"user\",instance=~\".*Alertmanager\"}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"system\",instance=~\".*Alertmanager\"}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=~\".*irq\",instance=~\".*Alertmanager\"}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=~\".*Alertmanager\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal{instance=~\".*Alertmanager\"} - node_memory_MemFree{instance=~\".*Alertmanager\"} - (node_memory_Cached{instance=~\".*Alertmanager\"} + node_memory_Buffers{instance=~\".*Alertmanager\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached{instance=~\".*Alertmanager\"} + node_memory_Buffers{instance=~\".*Alertmanager\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree{instance=~\".*Alertmanager\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal{instance=~\".*Prometheus\"} - node_memory_SwapFree{instance=~\".*Prometheus\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Disk Space Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail{instance=~\".*Alertmanager\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\".*Alertmanager\",device!~'rootfs'})",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Alertmanager Failed Notifications",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "alertmanager_notifications_failed_total",
       "legendFormat": "{{ integration }}"
      }
     ]
    },
    {
     "title": "Total Notifications",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "alertmanager_notifications_total",
       "legendFormat": "{{ integration }}"
      }
     ]
    },
    {
     "title": "Alertmanager Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "alertmanager_build_info", "legendFormat": "{{ version }}" }
     ]
    },
    {
     "title": "Alert Silences",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "alertmanager_silences", "legendFormat": "{{ state }}" }
     ]
    },
    {
     "title": "Alertmanager last config reload success",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "alertmanager_config_last_reload_successful"
      }
     ]
    },
    {
     "title": "Alert Receivers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "alertmanager_receivers" }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "alertmanager_alerts", "legendFormat": "{{ state }}" }
     ]
    },
    {
     "title": "Notification Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(alertmanager_notification_latency_seconds_sum[5m])",
       "legendFormat": "{{ integration }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Storage Usage (GB)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ]
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"iowait\",instance=~\".*Grafana\"}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"user\",instance=~\".*Grafana\"}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"system\",instance=~\".*Grafana\"}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=~\".*irq\",instance=~\".*Grafana\"}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\".*Prometheus\"}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=~\".*Grafana\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal{instance=~\".*Grafana\"} - node_memory_MemFree{instance=~\".*Grafana\"} - (node_memory_Cached{instance=~\".*Grafana\"} + node_memory_Buffers{instance=~\".*Grafana\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached{instance=~\".*Grafana\"} + node_memory_Buffers{instance=~\".*Grafana\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree{instance=~\".*Grafana\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal{instance=~\".*Prometheus\"} - node_memory_SwapFree{instance=~\".*Prometheus\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Disk Space Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail{instance=~\".*Grafana\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\".*Grafana\",device!~'rootfs'})",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logstash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"iowait\",instance=~\".*Logstash\"}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"user\",instance=~\".*Logstash\"}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=\"system\",instance=~\".*Logstash\"}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu{mode=~\".*irq\",instance=~\".*Logstash\"}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=~\".*Logstash\"}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\".*Logstash\"}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=~\".*Logstash\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal{instance=~\".*Logstash\"} - node_memory_MemFree{instance=~\".*Logstash\"} - (node_memory_Cached{instance=~\".*Logstash\"} + node_memory_Buffers{instance=~\".*Logstash\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached{instance=~\".*Logstash\"} + node_memory_Buffers{instance=~\".*Logstash\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree{instance=~\".*Logstash\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal{instance=~\".*Logstash\"} - node_memory_SwapFree{instance=~\".*Logstash\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Disk Space Usage (%)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail{instance=~\".*Logstash\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\".*Logstash\",device!~'rootfs'})",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  }
 ]
}