{
 "title": "test dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Free Memory (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal{job=\"EC2 Node Exporter\"} - node_memory_MemFree{job=\"EC2 Node Exporter\"}) / (node_memory_MemTotal{job=\"EC2 Node Exporter\"} )) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node File system Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_size{job=\"EC2 Node Exporter\"}) / 1048576",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu{job=\"EC2 Node Exporter\",mode=\"system\"}[5m])) * 100",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum by (instance) (rate(node_cpu{job=\"EC2 Node Exporter\",mode=\"user\"}[5m])) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Requests total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_requests_total{job=\"EC2 Node Exporter\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}