{
 "title": "Network Statistics",
 "description": "bytes/packets transmit/receive",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes - transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{job=\"EC2 Node Exporter\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Bytes - receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{job=\"EC2 Node Exporter\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Packets - transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets{job=\"EC2 Node Exporter\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Packets - receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{job=\"EC2 Node Exporter\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  }
 ]
}