{
 "title": "Process Exporter",
 "description": "Process metrics exported by https://github.com/ncabatoff/process-exporter.",
 "tags": [ "OS" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Heap Size (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes/ 1024 / 1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Allocated Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1024 / 1024",
     "legendFormat": "{{ instance }} {{ job }}"
    }
   ]
  },
  {
   "title": "Virtual Memory Size (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / 1024 / 1024",
     "legendFormat": "{{ instance }} {{ job }}"
    }
   ]
  }
 ]
}