---
#
# Mount EBS volume to EC2 filesystem
#
- hosts: "{{ ip }}"
  remote_user: ec2-user
  vars_files:
    - ../../output.yml
  tasks:
    - name: Make xfs filesystem in EBS
      command: mkfs -t xfs -f /dev/xvdf
      become: yes

    - name: Make directory to mount
      file:
        path: "{{ mount_location }}"
        state: directory

    - name: Mount filesystem to directory
      command: mount /dev/xvdf {{ mount_location }}
      become: yes
