---
#
# Mount EBS volume to EC2 filesystem
#
- hosts: "{{ ip }}"
  remote_user: ec2-user
  vars_files:
    - ../../output.yml
  tasks:
    - name: Make xfs filesystem in EBS
      command: mkfs -t xfs -f /dev/xvdf
      become: yes
      
    - name: Mount filesystem to directory
      mount:
        path: "{{ mount_location }}"
        src: /dev/xvdf
        fstype: xfs
        state: mounted
      become: yes
